version: 2

build:
  image: documentation

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []

sphinx:
  builder: html
  configuration: docs/conf.py
