# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pyXsurf',
                'doc_host': 'https://vincenzooo.github.io',
                'git_url': 'https://github.com/vincenzooo/pyXsurf',
                'lib_path': 'pyXsurf'},
  'syms': {'pyXsurf.core': {'pyXsurf.core.foo': ('core.html#foo', 'pyXsurf/core.py')}}}